/**
 * Academic Export Utility for AI Study Companion
 * Provides clean downloads for Markdown, Anki-compatible Flashcard Decks,
 * and Print-Ready Academic Examination Papers and Notes.
 */

// Helper to download raw text files
export function downloadFile(filename: string, content: string, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// 1. Export Markdown file
export function exportToMarkdown(filename: string, markdownContent: string) {
  const safeFilename = filename.endsWith('.md') ? filename : `${filename}.md`;
  downloadFile(safeFilename, markdownContent, 'text/markdown;charset=utf-8');
}

// 2. Export Flashcard deck to Anki-compatible format (.txt / .csv)
export interface ExportCardItem {
  front: string;
  back: string;
}

export function exportFlashcardsToAnki(deckTitle: string, cards: ExportCardItem[]) {
  const safeTitle = deckTitle.trim().replace(/[^a-zA-Z0-9_-]/g, '_');
  
  // Format for Anki (Tab-separated with standard headers)
  let output = `#separator:tab\n#html:false\n#deck:${deckTitle}\n#tags:AI_Study_Companion\n`;
  
  for (const card of cards) {
    // Escape internal tabs and newlines for clean Anki row import
    const front = card.front.replace(/\t/g, ' ').replace(/\n/g, '<br>');
    const back = card.back.replace(/\t/g, ' ').replace(/\n/g, '<br>');
    output += `${front}\t${back}\n`;
  }

  downloadFile(`${safeTitle}_anki_deck.txt`, output, 'text/tab-separated-values;charset=utf-8');
}

// 3. Print / Save as PDF for Notes & Summaries
export interface PrintDocOptions {
  title: string;
  subtitle?: string;
  author?: string;
  content: string;
}

export function printFormattedDocument(options: PrintDocOptions) {
  const printWindow = window.open('', '_blank', 'width=850,height=1100');
  if (!printWindow) {
    alert('Please allow popups to print / save PDF.');
    return;
  }

  const currentDate = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(options.title)}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
  <style>
    @page {
      margin: 18mm;
      size: A4;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      margin: 0;
      padding: 20px;
    }
    .header-bar {
      border-bottom: 2px solid #2563eb;
      padding-bottom: 12px;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .title {
      font-size: 24px;
      font-weight: 800;
      color: #0f172a;
      margin: 0 0 4px 0;
    }
    .subtitle {
      font-size: 13px;
      color: #64748b;
      margin: 0;
    }
    .meta-box {
      text-align: right;
      font-size: 11px;
      color: #64748b;
    }
    .badge {
      display: inline-block;
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      background: #eff6ff;
      color: #2563eb;
      padding: 3px 8px;
      border-radius: 6px;
      border: 1px solid #bfdbfe;
      margin-bottom: 6px;
    }
    .content {
      font-size: 13px;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      font-size: 10px;
      color: #94a3b8;
      display: flex;
      justify-content: space-between;
    }
    @media print {
      body { padding: 0; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header-bar">
    <div>
      <span class="badge">AI Study Companion</span>
      <h1 class="title">${escapeHtml(options.title)}</h1>
      ${options.subtitle ? `<p class="subtitle">${escapeHtml(options.subtitle)}</p>` : ''}
    </div>
    <div class="meta-box">
      <div><strong>Date:</strong> ${currentDate}</div>
      ${options.author ? `<div><strong>Student:</strong> ${escapeHtml(options.author)}</div>` : ''}
    </div>
  </div>

  <div class="content">${escapeHtml(options.content)}</div>

  <div class="footer">
    <span>Generated by AI Study Companion</span>
    <span>Page 1 of 1</span>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 300);
    };
  </script>
</body>
</html>`;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}

// 4. Print / Save Exam Paper (Mock Exam with separate Answer Key)
export interface ExamQuestion {
  question: string;
  options: string[];
  correct_index?: number;
  correct_answer?: string;
  explanation?: string;
  marks?: number;
}

export function printMockExamPaper(examTitle: string, courseName: string, questions: ExamQuestion[]) {
  const printWindow = window.open('', '_blank', 'width=850,height=1100');
  if (!printWindow) {
    alert('Please allow popups to print / save exam paper.');
    return;
  }

  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const letters = ['A', 'B', 'C', 'D', 'E'];

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(examTitle)} - Mock Exam</title>
  <style>
    @page {
      margin: 18mm;
      size: A4;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.5;
      color: #1e293b;
      margin: 0;
      padding: 15px;
    }
    .exam-header {
      text-align: center;
      border-bottom: 2px solid #0f172a;
      padding-bottom: 15px;
      margin-bottom: 20px;
    }
    .exam-header h1 {
      font-size: 20px;
      font-weight: 900;
      margin: 0 0 4px 0;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .exam-header h2 {
      font-size: 14px;
      font-weight: 600;
      color: #475569;
      margin: 0 0 10px 0;
    }
    .student-fields {
      display: flex;
      justify-content: space-between;
      font-size: 11px;
      font-weight: 600;
      margin-top: 12px;
      padding-top: 8px;
      border-top: 1px dashed #cbd5e1;
    }
    .question-block {
      margin-bottom: 16px;
      page-break-inside: avoid;
    }
    .q-text {
      font-size: 12px;
      font-weight: 700;
      margin-bottom: 6px;
      color: #0f172a;
    }
    .options-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 6px 16px;
      padding-left: 14px;
    }
    .option-item {
      font-size: 11px;
      color: #334155;
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .bubble {
      width: 14px;
      height: 14px;
      border: 1px solid #64748b;
      border-radius: 50%;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      font-size: 9px;
      font-weight: bold;
      color: #475569;
      shrink: 0;
    }
    .page-break {
      page-break-before: always;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 2px dashed #94a3b8;
    }
    .answer-key-header {
      font-size: 16px;
      font-weight: 800;
      color: #0f172a;
      margin-bottom: 15px;
      border-bottom: 1.5px solid #2563eb;
      padding-bottom: 6px;
    }
    .key-item {
      margin-bottom: 10px;
      font-size: 11px;
      padding: 6px 10px;
      background: #f8fafc;
      border-left: 3px solid #2563eb;
      border-radius: 4px;
      page-break-inside: avoid;
    }
    .key-ans {
      font-weight: 800;
      color: #1e3a8a;
    }
    .key-exp {
      margin-top: 2px;
      color: #64748b;
      font-style: italic;
    }
    @media print {
      body { padding: 0; }
    }
  </style>
</head>
<body>
  <div class="exam-header">
    <h1>${escapeHtml(courseName || 'Academic Course Examination')}</h1>
    <h2>${escapeHtml(examTitle)}</h2>
    <div style="font-size: 11px; color: #64748b;">
      Total Questions: ${questions.length} &nbsp;|&nbsp; Marks: ${questions.length * 2} &nbsp;|&nbsp; Date: ${dateStr}
    </div>
    <div class="student-fields">
      <div>Student Name: ____________________________________</div>
      <div>Roll / ID: __________________</div>
      <div>Score: _____ / ${questions.length * 2}</div>
    </div>
  </div>

  <!-- Questions Section -->
  <div class="questions-container">
    ${questions
      .map(
        (q, idx) => `
      <div class="question-block">
        <div class="q-text">${idx + 1}. ${escapeHtml(q.question)}</div>
        <div class="options-grid">
          ${q.options
            .map(
              (opt, optIdx) => `
            <div class="option-item">
              <span class="bubble">${letters[optIdx] || optIdx + 1}</span>
              <span>${escapeHtml(opt)}</span>
            </div>
          `
            )
            .join('')}
        </div>
      </div>
    `
      )
      .join('')}
  </div>

  <!-- Answer Key Section (Page Break) -->
  <div class="page-break">
    <div class="answer-key-header">
      🔑 Answer Key & Conceptual Solutions (For Instructor / Self-Evaluation)
    </div>
    ${questions
      .map(
        (q, idx) => {
          const resolvedIdx =
            q.correct_index !== undefined
              ? q.correct_index
              : q.options.findIndex((opt) => opt === q.correct_answer);
          const ansLetter = resolvedIdx >= 0 ? letters[resolvedIdx] : '✓';
          const ansText = resolvedIdx >= 0 ? q.options[resolvedIdx] : q.correct_answer || '';

          return `
      <div class="key-item">
        <div>
          <strong>Q${idx + 1}:</strong> Correct Option: <span class="key-ans">(${ansLetter}) ${escapeHtml(
            ansText
          )}</span>
        </div>
        ${
          q.explanation
            ? `<div class="key-exp">Explanation: ${escapeHtml(q.explanation)}</div>`
            : ''
        }
      </div>
    `;
        }
      )
      .join('')}
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 300);
    };
  </script>
</body>
</html>`;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}

function escapeHtml(text: string): string {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
